# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgstudentmod.ui'
#
# Created: Tue Jul 12 12:48:35 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DlgStudentMod(object):
    def setupUi(self, DlgStudentMod):
        DlgStudentMod.setObjectName("DlgStudentMod")
        DlgStudentMod.resize(522, 239)
        self.verticalLayout = QtGui.QVBoxLayout(DlgStudentMod)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(DlgStudentMod)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(DlgStudentMod)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.editSurname = QtGui.QLineEdit(DlgStudentMod)
        self.editSurname.setObjectName("editSurname")
        self.horizontalLayout_3.addWidget(self.editSurname)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(DlgStudentMod)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editName = QtGui.QLineEdit(DlgStudentMod)
        self.editName.setObjectName("editName")
        self.horizontalLayout.addWidget(self.editName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(DlgStudentMod)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(DlgStudentMod)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.editUsername = QtGui.QLineEdit(DlgStudentMod)
        self.editUsername.setObjectName("editUsername")
        self.horizontalLayout_2.addWidget(self.editUsername)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnBuildUsername = QtGui.QToolButton(DlgStudentMod)
        self.btnBuildUsername.setObjectName("btnBuildUsername")
        self.horizontalLayout_4.addWidget(self.btnBuildUsername)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(DlgStudentMod)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DlgStudentMod)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DlgStudentMod.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DlgStudentMod.reject)
        QtCore.QObject.connect(self.btnBuildUsername, QtCore.SIGNAL("clicked()"), DlgStudentMod.buildUsername)
        QtCore.QMetaObject.connectSlotsByName(DlgStudentMod)

    def retranslateUi(self, DlgStudentMod):
        DlgStudentMod.setWindowTitle(QtGui.QApplication.translate("DlgStudentMod", "Gestione Utenti", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DlgStudentMod", "Dati dell\'utente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DlgStudentMod", "Cognome", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DlgStudentMod", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DlgStudentMod", "Nome Utente", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBuildUsername.setText(QtGui.QApplication.translate("DlgStudentMod", "auto-assegna", None, QtGui.QApplication.UnicodeUTF8))

