# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgstudentimport.ui'
#
# Created: Thu Jul  7 11:23:42 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DlgStudentImport(object):
    def setupUi(self, DlgStudentImport):
        DlgStudentImport.setObjectName("DlgStudentImport")
        DlgStudentImport.resize(806, 619)
        DlgStudentImport.setBaseSize(QtCore.QSize(800, 600))
        self.verticalLayout = QtGui.QVBoxLayout(DlgStudentImport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblClass = QtGui.QLabel(DlgStudentImport)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lblClass.setFont(font)
        self.lblClass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblClass.setObjectName("lblClass")
        self.horizontalLayout.addWidget(self.lblClass)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableStudents = QtGui.QTableWidget(DlgStudentImport)
        self.tableStudents.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tableStudents.setProperty("showDropIndicator", True)
        self.tableStudents.setAlternatingRowColors(True)
        self.tableStudents.setRowCount(1)
        self.tableStudents.setColumnCount(4)
        self.tableStudents.setObjectName("tableStudents")
        self.tableStudents.setColumnCount(4)
        self.tableStudents.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableStudents.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableStudents.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableStudents.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableStudents.setHorizontalHeaderItem(3, item)
        self.tableStudents.horizontalHeader().setCascadingSectionResizes(False)
        self.tableStudents.horizontalHeader().setMinimumSectionSize(30)
        self.tableStudents.horizontalHeader().setSortIndicatorShown(False)
        self.tableStudents.verticalHeader().setCascadingSectionResizes(False)
        self.tableStudents.verticalHeader().setDefaultSectionSize(25)
        self.tableStudents.verticalHeader().setMinimumSectionSize(50)
        self.tableStudents.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tableStudents)
        self.line = QtGui.QFrame(DlgStudentImport)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnReload = QtGui.QToolButton(DlgStudentImport)
        self.btnReload.setObjectName("btnReload")
        self.horizontalLayout_3.addWidget(self.btnReload)
        self.btnFix = QtGui.QToolButton(DlgStudentImport)
        self.btnFix.setEnabled(False)
        self.btnFix.setObjectName("btnFix")
        self.horizontalLayout_3.addWidget(self.btnFix)
        self.btnCheck = QtGui.QToolButton(DlgStudentImport)
        self.btnCheck.setObjectName("btnCheck")
        self.horizontalLayout_3.addWidget(self.btnCheck)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnImport = QtGui.QToolButton(DlgStudentImport)
        self.btnImport.setObjectName("btnImport")
        self.horizontalLayout_3.addWidget(self.btnImport)
        self.btnDialog = QtGui.QDialogButtonBox(DlgStudentImport)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDialog.sizePolicy().hasHeightForWidth())
        self.btnDialog.setSizePolicy(sizePolicy)
        self.btnDialog.setOrientation(QtCore.Qt.Horizontal)
        self.btnDialog.setStandardButtons(QtGui.QDialogButtonBox.Cancel)
        self.btnDialog.setCenterButtons(False)
        self.btnDialog.setObjectName("btnDialog")
        self.horizontalLayout_3.addWidget(self.btnDialog)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(DlgStudentImport)
        QtCore.QObject.connect(self.btnDialog, QtCore.SIGNAL("accepted()"), DlgStudentImport.accept)
        QtCore.QObject.connect(self.btnDialog, QtCore.SIGNAL("rejected()"), DlgStudentImport.reject)
        QtCore.QObject.connect(self.btnReload, QtCore.SIGNAL("clicked()"), DlgStudentImport.tableReload)
        QtCore.QObject.connect(self.btnCheck, QtCore.SIGNAL("clicked()"), DlgStudentImport.tableCheck)
        QtCore.QObject.connect(self.btnImport, QtCore.SIGNAL("clicked()"), DlgStudentImport.tableImport)
        QtCore.QObject.connect(self.tableStudents, QtCore.SIGNAL("itemChanged(QTableWidgetItem*)"), DlgStudentImport.tableItemChanged)
        QtCore.QMetaObject.connectSlotsByName(DlgStudentImport)

    def retranslateUi(self, DlgStudentImport):
        DlgStudentImport.setWindowTitle(QtGui.QApplication.translate("DlgStudentImport", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lblClass.setText(QtGui.QApplication.translate("DlgStudentImport", "Classe ", None, QtGui.QApplication.UnicodeUTF8))
        self.tableStudents.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("DlgStudentImport", "Cognome", None, QtGui.QApplication.UnicodeUTF8))
        self.tableStudents.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("DlgStudentImport", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.tableStudents.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("DlgStudentImport", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.tableStudents.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("DlgStudentImport", "Classe", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReload.setText(QtGui.QApplication.translate("DlgStudentImport", "Ricarica il file", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFix.setText(QtGui.QApplication.translate("DlgStudentImport", "Auto-Correggi", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheck.setText(QtGui.QApplication.translate("DlgStudentImport", "Ricontrolla", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImport.setText(QtGui.QApplication.translate("DlgStudentImport", "Esegui Importazione", None, QtGui.QApplication.UnicodeUTF8))

