# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgteachermod.ui'
#
# Created: Tue Jul 12 16:42:47 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DlgTeacherMod(object):
    def setupUi(self, DlgTeacherMod):
        DlgTeacherMod.setObjectName("DlgTeacherMod")
        DlgTeacherMod.resize(522, 721)
        self.verticalLayout = QtGui.QVBoxLayout(DlgTeacherMod)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(DlgTeacherMod)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(DlgTeacherMod)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.editSurname = QtGui.QLineEdit(DlgTeacherMod)
        self.editSurname.setObjectName("editSurname")
        self.horizontalLayout_3.addWidget(self.editSurname)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(DlgTeacherMod)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editName = QtGui.QLineEdit(DlgTeacherMod)
        self.editName.setObjectName("editName")
        self.horizontalLayout.addWidget(self.editName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(DlgTeacherMod)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(DlgTeacherMod)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.editUsername = QtGui.QLineEdit(DlgTeacherMod)
        self.editUsername.setObjectName("editUsername")
        self.horizontalLayout_2.addWidget(self.editUsername)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnBuildUsername = QtGui.QToolButton(DlgTeacherMod)
        self.btnBuildUsername.setObjectName("btnBuildUsername")
        self.horizontalLayout_4.addWidget(self.btnBuildUsername)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_5 = QtGui.QLabel(DlgTeacherMod)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lstClasses = QtGui.QListWidget(DlgTeacherMod)
        self.lstClasses.setObjectName("lstClasses")
        self.verticalLayout.addWidget(self.lstClasses)
        self.buttonBox = QtGui.QDialogButtonBox(DlgTeacherMod)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DlgTeacherMod)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), DlgTeacherMod.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DlgTeacherMod.reject)
        QtCore.QObject.connect(self.btnBuildUsername, QtCore.SIGNAL("clicked()"), DlgTeacherMod.buildUsername)
        QtCore.QMetaObject.connectSlotsByName(DlgTeacherMod)

    def retranslateUi(self, DlgTeacherMod):
        DlgTeacherMod.setWindowTitle(QtGui.QApplication.translate("DlgTeacherMod", "Gestione Utenti", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DlgTeacherMod", "Dati dell\'utente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DlgTeacherMod", "Cognome", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DlgTeacherMod", "Nome", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DlgTeacherMod", "Nome Utente", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBuildUsername.setText(QtGui.QApplication.translate("DlgTeacherMod", "auto-assegna", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DlgTeacherMod", "Lista delle classi assegnate all\'insegnante :", None, QtGui.QApplication.UnicodeUTF8))

